# Generated by Django 5.1.3 on 2024-11-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='year',
            new_name='overall',
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='snaps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('LT', 'Left Tackle'), ('LG', 'Left Guard'), ('C', 'Center'), ('RG', 'Right Guard'), ('RT', 'Right Tackle'), ('LE', 'Left End'), ('RE', 'Right End'), ('DT', 'Defensive Tackle'), ('LOLB', 'Left Outside Linebacker'), ('MLB', 'Middle Linebacker'), ('ROLB', 'Right Outside Linebacker'), ('CB', 'Cornerback'), ('FS', 'Free Safety'), ('SS', 'Strong Safety'), ('K', 'Kicker'), ('P', 'Punter')], max_length=10),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=4)),
                ('games_started', models.IntegerField(default=0)),
                ('passing_attempts', models.IntegerField(default=0)),
                ('passing_completions', models.IntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('touchdowns_passed', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('rushing_attempts', models.IntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
