# Generated by Django 5.1.3 on 2024-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_year_player_overall_player_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='YAC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='broken_tackles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='drops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='fumbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='longest_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='receiving_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='rushing_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='sacks_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='twenty_yard_rushes',
            field=models.IntegerField(default=0),
        ),
    ]
