# Generated by Django 5.1.3 on 2024-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('completions', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(blank=True, null=True)),
                ('yards', models.IntegerField(blank=True, null=True)),
                ('yards_per_attempt', models.FloatField(blank=True, null=True)),
                ('touchdowns', models.IntegerField(blank=True, null=True)),
                ('interceptions', models.IntegerField(blank=True, null=True)),
                ('passer_rating', models.FloatField(blank=True, null=True)),
                ('rush_attempts', models.IntegerField(blank=True, null=True)),
                ('rush_yards', models.IntegerField(blank=True, null=True)),
                ('yards_per_carry', models.FloatField(blank=True, null=True)),
                ('rush_tds', models.IntegerField(blank=True, null=True)),
                ('receptions', models.IntegerField(blank=True, null=True)),
                ('receiving_yards', models.IntegerField(blank=True, null=True)),
                ('yards_per_catch', models.FloatField(blank=True, null=True)),
                ('receiving_tds', models.IntegerField(blank=True, null=True)),
                ('plays_from_scrim', models.IntegerField(blank=True, null=True)),
                ('yards_from_scrim', models.IntegerField(blank=True, null=True)),
                ('avg_yards_per_play', models.FloatField(blank=True, null=True)),
                ('scrimmage_tds', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
